services:
  myapi:
    build: 
      context: ..
      dockerfile: .deploy/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=PreProduction
      - ASPNETCORE_URLS=http://+:5000
