name: "Format, Build & Test"

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  checks: write

jobs:
  format:
    name: "Code Format Check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dotnet-setup
      - name: "Code format check"
        run: dotnet format --verify-no-changes

  test:
    needs: format
    name: "Run Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dotnet-setup
